config/routes.rb
Deals::Application.routes.draw do

  devise_for :people
  resources :deals do
    resources :transactions
  end

  root :to => "deals#index"

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :person
  has_many :transactions
  validates :title, :presence =>true
  validates :description,:presence =>true
  validates :unit,:presence =>true
  validates :discounted_price,:presence =>true
  validates :expiry_date, :presence=> true
  validates_datetime :expiry_date, :on_or_after => DateTime.now
  validates :actual_price,:presence =>true
  validates :image_url,:presence =>true
  validates_numericality_of :unit
  validates_numericality_of :discounted_price
  after_initialize :date_today

  private
  def date_today
    self.expiry_date ||= DateTime.now
  end

  def date_tomorrow
  DateTime.now + 1.day
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:fullname,:username,:phonenumber,:notify

  has_many :deals
  has_many :transactions
  validates :email, :presence => true
  validates :password, :presence => true
  validates :username, :presence => true
  validates :fullname, :presence => true
  validates :phonenumber, :presence => true
  validates_uniqueness_of :email
  validates_uniqueness_of :username
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  belongs_to :person
  belongs_to :deal
  validates :unit,:presence =>true
  validates :card_number,:presence =>true
    validates :payment,:presence =>true
  validates_numericality_of :card_number
  validates :card_number, :length => {:minimum => 13, :maximum => 16}
  validates_numericality_of :unit


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
 before_filter :authenticate_person!, :except => [:index,:show]
  def new
    @deal = Deal.new
  end

  def show
    @deal = Deal.find(params[:id])
  end

  def index

    @deals = Deal.all
  end

  def create
    @deal = Deal.new(params[:deal])
    if @deal.discounted_price > @deal.actual_price
      render 'new'
      flash[:notice] = "Discounted Price is more than the actual price"
    end
      @deal.person_id =current_person.id
      if @deal.save
        flash[:notice]="Congratulations! Your deal has been created"
        redirect_to :root
      else
        flash[:alert]="Error While creating deal,please try later"
        render 'new'
      end

  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
#before_filter :check_unit,:only => :create
  def new
    @deal =Deal.find(params[:deal_id])
    @transaction = @deal.transactions.new
  end

  def create
    @deal =Deal.find_by_id(params[:deal_id])
    @transaction = @deal.transactions.new(params[:transaction])
    if @transaction.unit == 0                                     #check if the amount of unit applied is zero
      flash.now[:alert] = "Unit is empty!"
      render 'new'
    else
        if check_unit(@transaction.unit)                          #calculating payment
            @transaction.payment = @transaction.unit*@deal.discounted_price
            @transaction.person = current_person
            if @transaction.save
              flash[:notice] = "Transaction successfull!"
              @deal.unit = @deal.unit-@transaction.unit             #calculate remaining units in stock
              @deal.save
              redirect_to deals_path
            else
              flash.now[:alert]= "o0ps something went wrong!! try again"
              render 'new'
            end
        else
          flash.now[:notice] = "YOu stupid!! Not enough Stocks"
          render 'new'
        end
    end

  end

def check_unit(transaction_unit)      #to check if the applied number of unit is more than stock
  if transaction_unit <= @deal.unit
    return true;
  else
    return false;
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def foot_out
   [ '<div id="foot-out">',
        '<div id="foot">',
            '<a href="http://www.sprout-technology.com" title="Sprout" class="credit">Powered by SprOut Technology</a>',
            '<ul class="footlist">',
                '<li class="primary"><h4><a href="" title="">How it Works</a></h4>',
                '<p>Go Click Create a Deal or Select Any Deal to View About The Deal </p>',
                '</li>',
                '<li class="primary"><h4><a href="" title="">Partners</a></h4>',
                '<ul>',
                    '<li><a href="www.merodeal.com" title="">mero Deal</a></li>',
                    '<li><a href="www.harilo.com" title="">Harilo</a></li>',
                    '<li><a href="www.mucha.com" title="">Muncha</a></li>',
                    '<li><a href="www.mero-it.com" title="">MeroIT</a></li>',
                '</ul></li>',
                '<li class="primary"><h4>Contact Us</h4>',
                '<p>juno street california -19  <a href="" title="">Aliquam</a> in tellus risus, at fermentum neque. Nulla accumsan dictum est, a sc </p>',
                '</li>',
            '</ul>',
        '</div>',
    '</div>'].join(' ').html_safe

  end
  def check_if_logged_in
    if person_signed_in?
      return link_to("Sign Out",destroy_person_session_path)
    else
      link_to("sign In",new_person_session_path);
    end
  end
end

app/helpers/deal_helper.rb
module DealHelper
  def deal_data(deal)
    [
    '<div class="dealdata">',
            '<div class="time">',
                '<h5>Time remaining</h5>',
                '<div class="clock"><span id = "cntdwn">00:00:00</span></div>',
            '</div>',
            '<div class="price">',
                '<div class="prices">',
                    '<div class="value">Rs',
                    deal.actual_price,
                    '<span class="c">.00</span>',
                    '</div>',
                    '<div class="dealprice">Rs',
                     deal.discounted_price,
                     '<span class="c">.78</span></div>',
                    '</div>',
            '</div>',
            '<div class="buynow">',
                link_to("Buy Now",new_deal_transaction_path(deal),:id =>"buy-now"),
            '</div>',
'</div>'].join(' ').html_safe
  end

  def display_deals(deal)
    ['<div class = "display-deals">',
      '<span class = "deal-content"><div class = "display-title">',
      link_to(deal.title,deal_path(deal)),
      '</div>',
      '<div class = "display-description" >',
        deal.description,
         '</div></span>',
      '<span class= "deal-thumbnail">',
       image_tag('Mock_ups.png',:size=>"60x60"),
        '</span>',
    '</div>'
    ].join(" ").html_safe
  end
end

app/helpers/transaction_helper.rb
module TransactionHelper
end

app/views/deals/create.html.erb
<h1>Deal#create</h1>
<p>Find me in app/views/deal/create.html.erb</p>

app/views/deals/destroy.html.erb
<h1>Deal#destroy</h1>
<p>Find me in app/views/deal/destroy.html.erb</p>

app/views/deals/edit.html.erb
<h1>Deal#edit</h1>
<p>Find me in app/views/deal/edit.html.erb</p>

app/views/deals/index.html.erb
<div class = "action-title">More Deals</div>
<% @deals.each do |deal| %>
<%= display_deals(deal) %>
<% end %>

app/views/deals/new.html.erb
<div class = "action-title">Create a deal</div>
<%= semantic_form_for @deal do |d|%>
<%=d.inputs :title,:description,:unit,:expiry_date,:discounted_price,:actual_price,:image_url%>
<%=d.buttons%>
<%end%>

app/views/deals/show.html.erb
    <%= deal_data(@deal) %>
    <%= javascript_tag "TargetDate = '#{@deal.expiry_date.to_datetime}';"%>
    <h3>Grab This Deal!! <%=link_to("more deals",deals_path,:class =>'h')%></h3>
    <h2><%= @deal.title %></h2>
    <img src = "../images/citrus-fruit.jpg" alt="" class="dealimage" />
    <div class = "deal-desc">
    <h4>About this deal</h4>
    <p><%= @deal.description %></p>
    </div>
    <div class = "deal-info">
    <p class= "deal-owner">Deal Created By :- <%= @deal.person.username%></p>
    <p class = "unit-left">Units Left :-<%=@deal.unit%></p>
    </div>
    <div id = "secondary-items">
    <ul class = "btns">
    <li><a href = "" title="">share</a></li>
    </ul>
    </div>

app/views/deals/update.html.erb
<h1>Deal#update</h1>
<p>Find me in app/views/deal/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deals</title>
  <%= stylesheet_link_tag 'default','style','formtastic','formtastic_changes' %>
  <%= javascript_include_tag 'jquery.min','application' %>

  <%= csrf_meta_tag %>
</head>
<body>
  <div id="wrap">
    <h1><%=link_to("Deals.com",deals_path,:class=>'title-link') %>
      <%= link_to "Create a Deal",new_deal_path, :class => 'how' -%>
      <label class='username'><%= check_if_logged_in%></label>
    </h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
 </div>
  <!-- end of wrapper div -->

<%= foot_out %>
    <div id="sign-out">
        <div id="sign-up">
            <p>enter your email address and we will send you deals:</p>
            <form action="">
            <ul>
                <li class="field"><input type="text" /></li>
                <li class="btn"><a href=""><img src="../images/btn-sign-go.gif"/></a></li>
            </ul>
            </form>
        </div>
    </div>
</body>
</html>
<span><script type="text/javaScript" src="../javascripts/countdown.js"></script></span>

app/views/transactions/_form.html.erb
<%=semantic_form_for([@deal,@transaction]) do |f|%>
  <%=f.inputs :unit,:card_number %>
  <%=f.buttons%>
<%end%>

app/views/transactions/new.html.erb
<%= render 'form'%>